### ISSUE TITLE
Grajenje URL-jev in predloge

### ISSUE THREAD

**Issue by jaanos** [jasapozne/Nogometna_liga#1]
Svetujem, da v svoj repozitorij dodaste še program [`bottleext.py`](https://github.com/jaanos/OPB-bottle/blob/master/bottleext.py) in iz njega uvažate namesto iz `bottle.py`. Tako bo mogoče grajenje URL-jev s funkcijo `url`, s čimer boste omogočili, da projekt teče tudi na Binderju. Za več podrobnosti si poglejte MatejRojec/Gamma#1.

Vidim tudi, da imate v vsaki predlogi celotno ogrodje - tj., osnovna koda HTML se vam ponavlja, tako da bi bilo kakršnokoli spremembo narediti na vseh predlogah. Namesto tega predlagam, da imate eno predlogo s skupno osnovo, v ostalih predlogah pa jo vključite z `rebase`, da vam je ni potrebno ponavljati. Poglejte si, kako je to urejeno na vzorčnem projektu.

**Comment by zigagartner** [comment]
Pozdravljeni,

najlepša hvala za napotke. Stvari smo popravili in menimo, da smo s projektom zaključili. Edino težavo nam predstavlja Binder, saj ne deluje, kljub temu da smo uredili vse URL-je, sporočilo ob napaki pa ni najbolj pomenljivo, zato vas prosimo za pomoč.

Lep pozdrav,
Žiga, Jaša, Mykola

**Comment by jaanos** [comment]
Projekta ne morem pognati niti lokalno - težava je v tem, da poskuša podatke za prijavo na bazo dobiti iz programa `auth.py`, ki ga seveda nimate na repozitoriju. Kolikor vidim, so pravice uporabnika `javnost` ustrezno določene, tako da bo za zagon (tudi na Binderju) zadostovalo, da namesto iz `auth` uvažate iz `auth_public`.

Sicer pa imam še sledeče pripombe:

* Pri registraciji pride do napake, če poskusim vnesti dejanski EMŠO. Za stolpec `emso` v tabeli `oseba` ste namreč uporabili tip `INTEGER`, za katerega pa so 13-mestna števila prevelika. Glede na to, da se EMŠO lahko začne tudi z ničlo, bo bolje zanj uporabiti tip `TEXT`; za glavni ključ pa bo bolje uporabiti nek ID s tipom `SERIAL` (reference nanj naj bodo tipa `INTEGER`) - za stolpec `emso` lahko potem uporabite določilo `UNIQUE`. Morda pa EMŠO sploh ne potrebujete, pa so ključi oseb enostavno ID-ji, ki se določijo samodejno, in tako tega polja niti ni na obrazcu za registracijo. Mimogrede, če tako naredite, pri uvozu podatkov teh ID-jev ne določajte eksplicitno (naj se sami generirajo), da bo števec ustrezno nastavljen (lahko ga pa po uvozu ročno nastavite).

* V tabeli `zaposlen` manjka glavni ključ - tako kot v tabeli `igralec` naj bo to `emso` (oziroma ID glede na zgornji komentar - tukaj seveda tipa `INTEGER`).

* V tabelah `igralec` in `zaposlen` imate nekaj stolpcev tipa `TEXT`, ki pa vsebujejo številske vrednosti - ti naj bodo ustreznega številskega tipa (pri denarnih vrednostih bodo seveda številke brez znaka `€` - za njegov prikaz naj poskrbi aplikacija).

* Prikaz lestvice ne deluje, saj poskušate brisati in ustvarjati poglede, za kar uporabnik `javnost` nima pravic (kar je tudi smiselno). Pogledov ni potrebno ustvariti vsakič znova, pač pa jih imate lahko že pripravljene vnaprej (tj., ustvarite jih, ko ustvarjate tabele). Tako lahko za prikaz lestvice enostavno naredite poizvedbo na obstoječih pogledih.

**Comment by zigagartner** [comment]
Pozdravljeni,

popravili smo vse pripombe, razen prve, saj želimo, da bi bil EMŠO naš primarni identifikator oseb, vseeno smo tipe povsod spremenili v TEXT. Poleg tega je v neki fazi binder ponovno prenehal delovati, zanima nas, če mogoče zaradi tega, ker smo v html datoteke dodali kodo **&euro;**, saj  po odstranitvi Binder spet deluje.


Lep pozdrav,
Žiga, Jaša, Mykola

**Comment by jaanos** [comment]
V redu, bom dodal povezavo do projekta na repozitorij predmeta. Če se še niste, se lahko z @alenFMF domenite za termin zagovora. Če boste do takrat še kaj spreminjali, mi javite, da posodobim povezavo.

Kar se tiče Binderja, se včasih zgodi, da se stran naloži, preden se uspe aplikacija zagnati, in tedaj pride do napake. V tem primeru zadostuje ponovno nalaganje strani. Sem poskusil in mi je Binder deloval tudi pri commitu 4cc558e88bd860d8b2ec1fe7f641805bc19a9a56, tako da znak € ni težava.

Še vedno se pa pojavi težava pri registraciji, če se vnese neobstoječ EMŠO. Kolikor vidim, gre za to, da ponekod preusmerjate na `url('prijava')` in `url('registracija')`, vendar funkcij s tema imenoma nimate - potrebno bo torej uporabiti `url('prijava_get')` in `url('registracija_get')`.

Pri urejanju osebe imate pri EMŠO možnost izbire obstoječih EMŠOv - seveda bo vsaka druga izbira od trenutne sprožila napako zaradi ponovljenega EMŠO. Morda bi bilo smiselno imeti vnosno polje, da se vnese druga vrednost, a ker imate EMŠO kot reference, bi bilo potrebno ob spremembi poskrbeti za spremembe vseh referenc (kar bi lahko naredili z nastavitvijo `CASCADE` na referencah). Lahko pa enostavno ne dovolite spremembe EMŠOv (tj., tega polja na obrazcu za urejanje ne bo).

Pri dodajanju tekme in zadetka mora uporabnik vnesti ID. Bolje bi bilo, da imate za to stolpca tipa SERIAL, tako da se ID ob vstavljanju sam generira.

Še to: ko pride do napake pri poizvedbi (npr. pri poskusu spreminjanja EMŠO na drugo že obstoječo vrednost), transakcije ne prekličete, zato baza ne sprejema novih poizvedb in aplikacija neha delovati. Da se temu izognete, bo potrebno pri vsaki transakciji, kjer lahko pride do napake, ob napaki ustrezno ukrepati, npr.
```python
try:
    cur.execute("""
                   UPDATE igralec SET pozicija = %s, visina = %s, teza = %s, vrednost = %s,
                   zacetek_pogodbe = %s, konec_pogodbe = %s, emso = %s WHERE emso = %s;
                """, (pozicija, visina, teza, vrednost, zacetek_pogodbe, konec_pogodbe, novi_emso, staro[6]))
    conn.commit()
except psycopg2.DatabaseError:
    conn.rollback() # transakcija se prekliče, zdaj so možne nove poizvedbe
    nastaviSporocilo("Prišlo je do napake")
    redirect(url('igralec_uredi_get', emso=staro[6]))
redirect(url('igralec'))
```
Koristno bi bilo poskrbeti tudi, da se v takih primerih vrednosti v obrazcu nastavijo na vnesene vrednosti (pri tem si lahko pomagate s piškotki, podobno kot za sporočilo o napaki).

**Comment by zigagartner** [comment]
Popravili smo omenjene stvari in prosimo, da posodobite povezavo.

**Comment by jaanos** [comment]
Kot vidim, so vse tabele v bazi pobrisane, tako da aplikacija trenutno ne deluje.

**Comment by zigagartner** [comment]
Tabele in podatke sem na novo uvozil, zdaj bi aplikacija morala delovati.

**Comment by jaanos** [comment]
V redu, sem dodal povezavo do projekta.

**Comment by zigagartner** [comment]
Hvala.
